### PR TITLE
Upgrade to 2017-02-19e

### PR DESCRIPTION
**Pull request by kelunik**
I followed https://www.dokuwiki.org/install:upgrade in two steps, see two commits.

First unpacking the new release over our current files and then deleting the old files.

### CODE REVIEW

**Comment by kelunik** [comment]
@cmb69 @bjori @Sobak

**Comment by cmb69** [comment]
Thanks! Had you any chance to test this?

**Comment by kelunik** [comment]
Yes, it's running on the new wiki server on a separate (non-public) virtual host. Didn't see any issues with viewing and editing of pages.

**Comment by cmb69** [comment]
Thanks again, Niklas!

**Comment by kelunik** [comment]
As it's merged, I'm going to update the live wiki, fine?

**Comment by cmb69** [comment]
> As it's merged, I'm going to update the live wiki, fine?

Doesn't that happen automagically, anymore?

**Comment by kelunik** [comment]
No idea.

**Comment by kelunik** [comment]
At least nothing updated yet and I didn't setup anything like that.

**Comment by cmb69** [comment]
At least formerly, changes to this repo have automatically been rolled out to the server. Not sure in which intervals, though – maybe once per day.

@bjori @Sobak What would have to be done for this wrt. new server?

**Comment by kelunik** [comment]
@cmb69 I'm pretty sure it wasn't setup, only for bugs.php.net. wiki.php.net still used SVN in the deployed version. It's now running the merged version from a fresh GitHub clone in `/srv/web-wiki`.

**Comment by salathe** [comment]
This could be outdated, but I thought the rsync machine pulled from Git regularly and the wiki machine would rsync the changes. But from @kelunik's description, this may no longer be the case?  It should certainly be (or, go back to being) automated in some way, if it is not right now.

**Comment by cmb69** [comment]
> It should certainly be (or, go back to being) automated in some way, if it is not right now.

Yes, by all means. Otherwise any commit to this repo would have to be manually synched.

**Comment by kelunik** [comment]
I don't think manual syncing is a problem. The commit frequency here is pretty low and only configuration changes and upgrades. It's better to manually check those are working than an automatic sync that activates them somewhere later.

**Pull request merged**
