### PR TITLE
Compatible with php7

### PR DESCRIPTION
**Pull request by matyhtf**

### CODE REVIEW

**Comment by kelunik** [comment]
How are these changes related to PHP 7 compatibility?

**Comment by matyhtf** [comment]
The error log will be reported under PHP7.

test.php
----
```php
class A
{
    function test($a)
    {
    }   
}

class B extends A
{
    function test($a, $b)
    {
    }  
}

(new B)->test("1234", 456);
```

output
----
```shell
php test.php 

Warning: Declaration of B::test($a, $b) should be compatible with A::test($a) in /data/webroot/testxx.php on line 15
```

**Comment by salathe** [comment]
If you are modifying any third-party code (e.g. dokuwiki, a plugin) please also create a patch file based on the upstream package and add it to the `systems` directory (like `systems/doodle-voting.diff`). This is so that our patches can be applied again when updating those third-party items.

**Comment by php-pulls** [comment]
**Comment on behalf of salathe at php.net:**

These changes were already applied in 5f35939989 and b57ed02d (https://github.com/php/web-wiki/compare/5f359399%5E...b57ed02d).

**Pull request closed without merging**
