### PR TITLE
updated include plugin to latest master

### PR DESCRIPTION
**Pull request by cmb69**
Hmm, I'm generally not happy to update to a master, but in this case it seems to be appropriate, because the last [official release](https://github.com/dokufreaks/plugin-include/releases) is from 2011-07-19, and in particular, is using a deprecated DokuWiki JS function (addInitEvent). Of course, it would be easy to replace this particular function, but there may be [other relevant bug fixes](https://www.dokuwiki.org/plugin:include#development) (and perhaps security patches) included.

To my knowledge, the include plugin is only used on a few pages (namely todo/php56 and doc/article/php_ide, the latter being already superseeded), so it might be an alternative to get rid of the plugin altogether. Then again, the plugin might be useful for the future.

Anyhow, during testing I didn't notice any problems.

### CODE REVIEW

**Comment by bjori** [comment]
I don't think anyone knows about this plugin or how it works.
The 5.6 todo is also fixed and can be replaced with the static content.

I think its agood idea to remove unused things.
That being said, if you think it should stay and be updated, I'm ok with that.

**Comment by cmb69** [comment]
@bjori Yes, 5.6 could be replaced, but what about 7.0? There's not yet the respective page, and AFAIK there's no release manager yet, but maybe they'll want to use it. It seems to be quite handy to be able to automatically include the implemented RFCs. On the other hand, a simple link might do as well.

@jpauli @Tyrael Thoughts?

**Comment by cmb69** [comment]
I have merged the PR, to be able to go ahead. Removing the plugin could be done later.

**Comment by Tyrael** [comment]
sorry for the late reply, yeah, I used this plugin for the php56 todo page, but I agree with @bjori that the less stuff we keep around the easier to maintain it, so +1 for removing the plugin.

**Comment by cmb69** [comment]
Okay, so I'll remove the plugin later. At first I want to get the editor fixed. :smile:

**Comment by cmb69** [comment]
I have removed the include plugin now, and replaced the include syntax with a copy of the respective content.

**Pull request merged**
